version: "3.3"

x-logging:
  &dev-logging
  driver: journald

services:
  traefik:
    restart: always
    image: "gcr.io/pentium-mavis/traefik:v2.6.1"
    container_name: "traefik"
    logging: *dev-logging
    pull_policy: if_not_present
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/tls/certificates.yaml"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - mavis
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../tls/:/tls/"


  mavis-apiserver:
    restart: always
    image: gcr.io/pentium-mavis/apiserver:1.0.test-697
    pull_policy: if_not_present
    container_name: mavis-apiserver
    depends_on:
      - mavis-postgres
    env_file:
      - .env
      - ../.env
    volumes:
      - ../../data/rdp-proxy:/opt/rdp-proxy:z
      - ../../data/ssh-proxy:/opt/ssh-proxy:z
      - ../../data/media:/opt/media:z
    expose:
      - "8000"
    networks:
      - mavis
    command: bash -c "python -m mavis.cli storage init && python -m mavis.cli db upgrade && uvicorn mavis.apiserver.main:app --host 0.0.0.0 --port 8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mavis-apiserver.service=mavis-apiserver@docker"
      - "traefik.http.services.mavis-apiserver.loadbalancer.server.port=8000"
      - "traefik.http.routers.mavis-apiserver.rule=(PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/apistatic`) || PathPrefix(`/openapi.json`) || PathPrefix(`/auth`) || PathPrefix(`/redoc`))"
      - "traefik.http.routers.mavis-apiserver.entrypoints=websecure"
      - "traefik.http.routers.mavis-apiserver.priority=2"
      - "traefik.http.routers.mavis-apiserver.tls=true"


  mavis-storage:
    image: gcr.io/pentium-mavis/minio
    pull_policy: if_not_present
    expose:
      - "9000"
      - "9001"
    networks:
      - mavis
    volumes:
      - ../../storage_data:/data:z
    env_file:
      - .env
      - ../.env
    environment:
      MINIO_VOLUMES: /data
    container_name: mavis-storage
    command: server --console-address ":9001" /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mavis-storage.loadbalancer.server.port=9000"
      - "traefik.http.routers.mavis-storage.rule=PathPrefix(`/assets/videos`)"
      - "traefik.http.routers.mavis-storage.entrypoints=websecure"
      - "traefik.http.routers.mavis-storage.service=mavis-storage@docker"
      - "traefik.http.routers.mavis-storage.priority=2"
      - "traefik.http.routers.mavis-storage.tls=true"
      - "traefik.http.routers.mavis-storage.middlewares=mavis-storage-media"
      - "traefik.http.middlewares.mavis-storage-media.addprefix.prefix=/media"
      - "traefik.http.services.mavis-storage-minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.mavis-storage-minio.rule=Host(`minio-${DOMAIN}`)"
      - "traefik.http.routers.mavis-storage-minio.entrypoints=websecure"
      - "traefik.http.routers.mavis-storage-minio.service=mavis-storage-minio@docker"
      - "traefik.http.routers.mavis-storage-minio.tls=true"
      - "traefik.http.routers.mavis-storage-minio.priority=2"


  mavis-f2e:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/f2e:1.0.test-697
    container_name: mavis-f2e
    depends_on:
      - mavis-apiserver
    env_file:
      - .env
      - ../.env
    networks:
      - mavis
    expose:
      - "3000"
    volumes:
      - ../../data/media:/usr/share/nginx/html/assets/videos:Z
    logging: *dev-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mavis-f2e.loadbalancer.server.port=3000"
      - "traefik.http.routers.mavis-f2e.rule=PathPrefix(`/`)"
      - "traefik.http.routers.mavis-f2e.entrypoints=websecure"
      - "traefik.http.routers.mavis-f2e.service=mavis-f2e@docker"
      - "traefik.http.routers.mavis-f2e.priority=1"
      - "traefik.http.routers.mavis-f2e.tls=true"

  mavis-postgres:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/postgres:12.3
    container_name: mavis-postgres
    volumes:
      - ../../data/maindb:/var/lib/postgresql/data:z
      - ../../backups/db:/backups:z
    env_file:
      - .env
      - ../.env
    networks:
      - mavis
    logging: *dev-logging

  mavis-ssh-proxy:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/ssh-proxy:1.0.test-697
    container_name: mavis-ssh-proxy
    depends_on:
      - mavis-postgres
    env_file:
      - ./.env
      - ../.env
    networks:
      - mavis
    expose:
      - "4002"
    volumes:
      - ../../data/ssh-proxy:/opt/ssh-proxy:z
    logging: *dev-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mavis-ssh-proxy.service=mavis-ssh-proxy@docker"
      - "traefik.http.services.mavis-ssh-proxy.loadbalancer.server.port=4002"
      - "traefik.http.routers.mavis-ssh-proxy.rule=PathPrefix(`/ssh`)"
      - "traefik.http.routers.mavis-ssh-proxy.entrypoints=websecure"
      - "traefik.http.routers.mavis-ssh-proxy.priority=3"
      - "traefik.http.routers.mavis-ssh-proxy.tls=true"


  mavis-rdpguacd:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/rdpguacd:1.0.test-697
    container_name: mavis-rdpguacd
    env_file:
      - ./.env
      - ../.env
    networks:
      - mavis
    expose:
      - "4822"




  mavis-rdp-proxy:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/rdp-proxy:1.0.test-697
    container_name: mavis-rdp-proxy
    depends_on:
      - mavis-postgres
      - mavis-apiserver
    env_file:
      - ./.env
      - ../.env
    networks:
      - mavis
    expose:
      - "4003"
    logging: *dev-logging
    volumes:
      - ../../data/rdp-proxy:/opt/rdp-proxy:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mavis-rdp-proxy.service=mavis-rdp-proxy@docker"
      - "traefik.http.services.mavis-rdp-proxy.loadbalancer.server.port=4003"
      - "traefik.http.routers.mavis-rdp-proxy.rule=PathPrefix(`/rdp`)"
      - "traefik.http.routers.mavis-rdp-proxy.entrypoints=websecure"
      - "traefik.http.routers.mavis-rdp-proxy.priority=2"
      - "traefik.http.routers.mavis-rdp-proxy.tls=true"


  mavis-pgweb:
    pull_policy: if_not_present
    restart: always
    container_name: mavis-pgweb
    restart: always
    image: gcr.io/pentium-mavis/sosedoff/pgweb
    links:
      - mavis-postgres:postgres
    env_file:
      - .env
      - ../.env
    depends_on:
      - mavis-postgres
    networks:
      - mavis
    expose:
      - "8081"
    logging: *dev-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mavis-pgweb.loadbalancer.server.port=8081"
      - "traefik.http.routers.mavis-storage-minio.rule=Host(`minio-${DOMAIN}`)"
      - "traefik.http.routers.mavis-pgweb.entrypoints=websecure"
      - "traefik.http.routers.mavis-pgweb.service=mavis-pgweb@docker"
      - "traefik.http.routers.mavis-pgweb.tls=true"
      - "traefik.http.routers.mavis-pgweb.priority=2"


  mavis-redis:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/redis:5.0
    container_name: mavis-redis
    networks:
      - mavis
    logging: *dev-logging

  mavis-task-runner:
    pull_policy: if_not_present
    image: gcr.io/pentium-mavis/apiserver:1.0.test-697
    container_name: mavis-task-runner
    volumes:
      - ../../logs/scripts:/app/logs/scripts:z
      - ../../logs:/app/logs
    depends_on:
      - mavis-redis
      - mavis-postgres
    env_file:
      - .env
      - ../.env
    ports: []
    command: "celery -A mavis.apiserver.main.celery_app worker --loglevel=info"
    networks:
      - mavis
    logging: *dev-logging
    labels:
      - "traefik.enable=false"

  mavis-beat:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/apiserver:1.0.test-697
    container_name: mavis-beat
    depends_on:
      - mavis-redis
      - mavis-postgres
    env_file:
      - .env
      - ../.env
    ports: []
    command: "celery --app=mavis.apiserver.main.celery_app beat -l info"
    networks:
      - mavis
    logging: *dev-logging
    labels:
      - "traefik.enable=false"

  mavis-flower:
    pull_policy: if_not_present
    restart: always
    image: gcr.io/pentium-mavis/apiserver:1.0.test-697
    container_name: mavis-flower
    depends_on:
      - mavis-postgres
    env_file:
      - .env
      - ../.env
    expose:
      - "5555"
    command: ["celery", "flower", "--app=mavis.apiserver.main.celery_app", "--broker=${CELERY_BROKER_URL}",
     "--basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"]
    networks:
      - mavis
    logging: *dev-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mavis-flower.loadbalancer.server.port=5555"
      - "traefik.http.routers.mavis-flower.rule=Host(`flower-${DOMAIN}`)"
      - "traefik.http.routers.mavis-flower.entrypoints=websecure"
      - "traefik.http.routers.mavis-flower.tls=true"
      - "traefik.http.routers.mavis-flower.service=mavis-flower@docker"
      - "traefik.http.routers.mavis-flower.priority=2"


networks:
  mavis:
    name: mavis
